services:
  futefatec:
    build: .
    container_name: futefatec_app
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
      - ADMIN_USER=adminfatec
      - ADMIN_PASSWORD=adminfatec2026 # Altere para a senha segura desejada na produção
    volumes:
      - futefatec_data:/app/data
      - futefatec_uploads:/app/uploads

volumes:
  futefatec_data:
    driver: local
  futefatec_uploads:
    driver: local

