services:
  - type: web
    name: futfatec
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8085"
      - key: ADMIN_USER
        value: "adminfatec"
      - key: ADMIN_PASSWORD
        value: "adminfatec2026"
